platform :ios, '5'
pod 'TestFlightSDK'
pod 'Facebook-iOS-SDK'
pod 'Parse-iOS-SDK'
pod 'hpple'
pod 'ReactiveCocoa'
pod 'TTTAttributedLabel'

target :test do
    link_with 'SebastiaanSchool Tests'

    pod 'OCMock'
end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Pods-Acknowledgements.plist', 'Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
