platform :ios, '5'
pod 'TestFlightSDK'
pod 'Facebook-iOS-SDK'
pod 'Parse-iOS-SDK'
pod 'hpple'
pod 'ReactiveCocoa'
pod 'TTTAttributedLabel'

target :test do
    link_with 'SebastiaanSchool Tests'

    pod 'OCMock'
end
