//
//  SebastiaanStyleKit.h
//  Sebastiaan School Icons
//
//  Created by Jeroen Leenarts on 29-10-14.
//  Copyright (c) 2014 Jeroen Leenarts. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface SebastiaanStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* broadcastIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* atIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* phoneIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* groupIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* idCardIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* receiptIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* keyIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* listIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* twitterIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* binocularsIconTargets;

// Drawing Methods
+ (void)drawBroadcastIconWithFrame: (CGRect)frame;
+ (void)drawAtIconWithFrame: (CGRect)frame;
+ (void)drawPhoneIconWithFrame: (CGRect)frame;
+ (void)drawGroupIconWithFrame: (CGRect)frame;
+ (void)drawIdCardIconWithFrame: (CGRect)frame;
+ (void)drawReceiptIconWithFrame: (CGRect)frame;
+ (void)drawKeyIconWithFrame: (CGRect)frame;
+ (void)drawListIconWithFrame: (CGRect)frame;
+ (void)drawTwitterIconWithFrame: (CGRect)frame;
+ (void)drawBinocularsIconWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfBroadcastIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfAtIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPhoneIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfGroupIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIdCardIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfReceiptIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfKeyIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfListIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfTwitterIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfBinocularsIconWithFrame: (CGRect)frame;

@end
